   PROJ := top
PIN_DEF := icePie.pcf
 DEVICE := up5k
 ADD_SRC := i2c.v \
				i2c_api.v \
				gfx_unit_bresenham.v \
				framebuffer.v \
				encoder.v \
				debounce.v \
				uart_demo.v
include ./main.mk


